catherinedevlin/ipython-sql

src/sql/parse.py

configparser is a module that has the constructor function so calling `configparser` before resulted in a `TypeError: 'module' object is not callable` error.
BTW, I was unable to run the tests to verify that this didn't break anything. I tried to follow the `HACKING.txt` instructions but ran into this:
```
$ python --version
Python 2.7.8
$ python bootstrap.py
Traceback (most recent call last):
File "bootstrap.py", line 105, in <module>
ws.find(pkg_resources.Requirement.parse(requirement)).location
AttributeError: 'NoneType' object has no attribute 'location'
```
Simply running `nosetest` I get `ERROR: Failure: NameError (name 'get_ipython' is not defined)`.

fixes configparser in python 2.x

---

src/sql/run.py

Just a couple of compatibility fixes for the CSV output function; in Python 3 there's no need for the encoding-decoding dance, as string objects are already unicode-aware. That fun job can be offloaded to the file stream object.

Fix CSV method to work with Python 3

---

src/sql/magic.py

Minor config help string fixes.
The intent is to go from this:
To this:

fix config help text formatting and typo

---

src/sql/magic.py
src/sql/run.py

Adds a new boolean config option column_local_vars  (default False). When true, instead of returning results into the `_` variable, the user's namespace is edited to add variables as lists of data, with names supplied by the query column names. This also obeys the config.autopandas options (returning pandas series instead of lists) and the config.feedback option (returning silently or printing a list of column names)
Minimal example:
```
In [1]: %load_ext sql
In [2]: %sql postgresql://localhost/test
Out[2]: 'Connected: None@test'
In [3]: %config SqlMagic.column_local_vars = True
In [4]: %sql select generate_series(1,5) xdata, random() ydata
5 rows affected.
Returning data to local variables [xdata, ydata]
In [5]: xdata
Out[5]: (1, 2, 3, 4, 5)
In [6]: ydata
Out[6]:
(0.953827208839357, …
```

New config option to return results directly to user namespace

---

src/sql/magic.py
src/tests/test_magic.py

Fixed a bug where variables in the local namespace would get leaked into the user namespace when the sql magic was used.

Fixed local_ns leak

---

src/sql/connection.py
src/sql/run.py

The 'commit' command executed in run.py causes a "connection busy" error for SQL Server. 
Since autocommit mode is the default transaction management mode of the SQL Server Database Engine, i.e., every Transact-SQL statement is committed or rolled back when it completes, the 'commit' in run.py is unnecessary.

Fix "connection busy with another command" error for SQL Server

---

src/sql/magic.py
src/tests/test_parse.py

to suppress warnings.  Both modules were separated from IPython around the same time so grouping the `ImportError`s should be fine.

prefer new traitlets packages

---

README.rst

It wasn't clear how to make a connection without explicitly typing out the username and password. This change adds a short section to the README which shows how to use the dollar-sign prefix to access variables in the %sql command.

Show how to securely access credentials in README

---

src/sql/magic.py

On Python 3, I came across the following error, when `autopandas` is set to `True`
`The truth value of a DataFrame is ambiguous.  Use a.empty, a.bool(), a.item(), a.any() or a.all().`
This is a fix for this, tested on my own fork.

Fix truth value of a DataFrame error

---

README.rst

This commit clarifies the issue raised in https://github.com/catherinedevlin/ipython-sql/issues/51.  
The issue is that the `displaylimit` config option does not work if the `autopandas` config option is set to true.
Please view the discussion in the issue for details.
I ran into this issue as well and spent some time digging into this problem. I don't think it is resolvable, but I do think including this note in the readme will save people time.

Update readme to address issue 51

---

README.rst
src/sql/magic.py
src/sql/run.py

I tried to connect hiverserver2 with [impyla](https://github.com/cloudera/impyla) but it caused an error on executing `commit` in `run.py`. To avoid this problem, I added a new config `autocommit` to set autocommit mode. See also #53 .

Add autocommit setting to connect HiveServer2 with impyla

---

src/sql/magic.py

confirmed failure in firefox and chrome for os x
The error I got was `TypeError: IPython.CodeCell.config_defaults is undefined`

commenting out code that dies in some browsers

---

setup.py

I hope I'm correct in this removal. My understanding is that we are unopinionated about which database should be used.

remove pgspecial as install_requires

---

src/sql/run.py

Fixing #103 by adding a blacklist of dialects that are restricted from using autocommit

Adding ClickHouse to autocommit blacklist

---

setup.py

Added utf-8 encoding, to fix the following error:
P.S. Thanks for the wonderful tool you've created! :+1: 
```python
Traceback (most recent call last):
File "setup.py", line 5, in <module>
README = open(os.path.join(here, 'README.rst')).read()
File "/anaconda/envs/nextgentel-recommender/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9375: ordinal not in range(128)
```

Update setup.py with encoding.

---

requirements.txt

- Pin version of `prettytable` to latest (`0.7.2`) as there seems to be a problem with the `7` release
I was unable to `poetry add --dev ipython-sql` without this.

Pin version of prettytable to allow poetry install

---

requirements.txt

It failed when running 'pip install -r requirement.txt'
PEP-440 says exact version specifier is '==' (double equal)
https://www.python.org/dev/peps/pep-0440/#version-specifiers

Fixed wrong version specifier

---

setup.py

In a previous commit(#136), @milesrichardson is pinning the `prettytable` dep version in `requirements.txt`.
PyPI indeed wrongly lists a non-existent version `7` for `prettytable`.
However, even after accounting for that in `requirements.txt`, it still leads to `ipython-sql` not being installable with eg `poetry`.
```
$ poetry add ipython-sql
[EnvCommandError]                                                                                                                 
Command ['python', '-m', 'pip', 'install', '--no-deps', '-U', 'prettytable==7'] errored with the following output:                                           
Collecting prettytable==7                                                                                                                      
ERROR: Could not find …
```

(actually :) Pin version of prettytable to allow poetry install

---

README.rst
src/sql/connection.py
src/sql/magic.py

This PR is to solve [issue 126](https://github.com/catherinedevlin/ipython-sql/issues/126) raised by @TobiasSkovgaardJepsen.
I add a config flag `SqlMagic.displaycon` which when set to `False` will suppress the printing of the connection string after executing any SQL statements.
Since connection credentials are often included in the SQAlchemy connection string, it is helpful to be able to suppress printing it.
```
In [1]: %load_ext sql
...: %sql sqlite:////home/jovyan/shared/sqlite-tutorial/chinook.db
...: %sql SELECT trackid, name, composer, unitprice FROM tracks LIMIT 5
...:
...:
* sqlite:////home/jovyan/shared/sqlite-tutorial/chinook.db
Done.
Out[1]:
[(1, 'For Those About To Rock (We Salute You)', 'Angus Young, Malcolm Young, Brian Johnson', 0.99),
(2, 'Balls to the Wall', None, …
```

Add SqlMagic option to suppress printing of connection string.

---

src/sql/run.py

We are trying to use the SQL magic with AWS Athena, we noticed that Athena doesn't support autocommit.

Added AWS Athena to the autocommit blacklist dialects

---

NEWS.txt
requirements-dev.txt
requirements.txt
setup.py
src/sql/magic.py
src/tests/run_tests.sh
tox.ini

Certain arguments cannot be passed directly via the DSN when connecting. One notable example is search_path when using the `psycopg2` driver to connect to a postgres database. These changes allow a user to pass a connect_args dict along with the dsn during the connection process.
For example this examples fails:
```
In [1]: %sql postgresql://user:pass@localhost:5432/db?search_path=myschema
(psycopg2.ProgrammingError) invalid dsn: invalid connection option "search_path"
```
The `connect_args` can either be passed as a literal json string or as a bindvar matching the other bindvar syntax in this project.
Aside: also fixed a previously failing test `test_persist` in `test_magic.py`

Support passing connect_args to sqlalchemy

---

src/sql/magic.py

Closes #80  , #79
Although line_magic automatically replaces variables, cell_magic does not.
```python
query = "name = 'bob'"
```
```sql
%%sql
select count(1) from users where {query}
```
To escape use multi-brackets:
```sql
%%sql
select '{{I'm in brackets}}'
```

support for variables in multi-line statements

---

src/sql/run.py
src/tests/test_magic.py

This PR adds a support to run queries written in files using the following syntax:
%sql filename
This is useful e.g. with excessively long queries that the user might want to keep as a separate file or when reusing existing codebase.

Add support for running queries from files

---

src/sql/run.py

Fixes upstream https://github.com/catherinedevlin/ipython-sql/issues/148 by adding "vertica" to dialects with broken commit

Fix upstream issue 148 with vertica dialect

---

README.rst
src/sql/parse.py

- Fixes the README.rst so that the ini config is displayed with line breaks as expected
- Fixes config reference pass in `_connection_string()` to enable parsing config section name correctly

Minor Fixes for dsn.ini

---

src/sql/run.py

Since Redshift is based on PostgreSQL, special commands for the latter work on the former. This PR lets PGSpecial be used for such commands when one is accessing a Redshift db.

Enable use of PGSpecial for Redshift databases

---

src/sql/run.py

Added ingres to the list of databases that are autocommit.
Sorted _COMMIT_BLACKLIST_DIALECTS tuple alphabetically.

Actian Avalanche, Actian X, Ingres, and Vector support

---

src/sql/run.py

Autocommit breaks bigquery operations because they have their [own restrictions on transactions](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-manipulation-language) and don't support commits.

Exclude bigquery dialect from autocommit

---

src/sql/magic.py

Hi Catherine, MySQL returns a DatabaseError instead of OperationalError. This also covers other exceptions like IntegrityError. Please add this to magic.py. Thanks for maintaining this library!
Best, Jens

Add DatabaseError in to handle MySQL exceptions correctly in magic.py

---

src/sql/connection.py

- This adds `@classmethod`, else `sql.connection.Connection._close(args.close)` from 
https://github.com/catherinedevlin/ipython-sql/blob/12f9742a0a4eded514cc95377c920330ccba5e72/src/sql/magic.py#L166
will get an error saying that descriptor argument is required. `@classmethod` will allow `self` to be passed through, and `args.close` will correctly pass as an argument for `descriptor`.
`descriptor` is a connection string.
- This removes `cls.connections.pop(conn.name)`, else it will have a key error when attempting to pop an invalid key from the dictionary of connections.  This line isn't necessary from what I can see.  Perhaps someone else with a different use case may need this can chime in after testing.

fix `%sql --close <sqlalchemy_connection_string>` error

---

src/sql/parse.py
src/tests/test_parse.py

The parser split off the first three elements of the cell, to check
if they have a connection string or push the result to a variable.
But if these elements weren't found, the components were glued back
together with spaces.  If one of these components was a line comment,
it ends up commenting out more than it should.
This solution tries splitting off bits to see if they match the
expected form.  But if they don't, it goes back to using the pre-
split string, thus preserving the original whitespace.  This should
allow the connection string and redirect to appear after any number
of newline characters, as long as they are still the first non-
whitespace elements in the cell.

Avoid replacing newlines with spaces early in the query
